# Generated by Django 3.2.23 on 2024-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_title',
            field=models.CharField(blank=True, choices=[('Grandmaster', 'Grandmaster'), ('King', 'King'), ('Queen', 'Queen'), ('Rook', 'Rook'), ('Bishop', 'Bishop'), ('Knight', 'Knight'), ('Pawn', 'Pawn')], default='', max_length=50, null=True, verbose_name='Title'),
        ),
    ]
