# Generated by Django 3.2.23 on 2024-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_title',
            field=models.CharField(blank=True, choices=[('Grandmaster', 'Grandmaster'), ('King', 'King'), ('Queen', 'Queen'), ('Rook', 'Rook'), ('Bishop', 'Bishop'), ('Knight', 'Knight'), ('Pawn', 'Pawn')], default='', max_length=50, null=True),
        ),
    ]
