# Generated by Django 3.2.23 on 2024-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Hikaru Nakamura', 'Hikaru Nakamura'), ('Magnus Carlsen', 'Magnus Carlsen')], max_length=20)),
                ('rating', models.IntegerField(help_text='Chess rating (ELO rating)')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
