# Generated by Django 3.2.23 on 2024-04-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='rating',
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
