# Generated by Django 3.2.23 on 2024-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0002_auto_20240416_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
