# Generated by Django 3.2.23 on 2024-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0003_giveaway_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Your chess rating (ELO rating)', null=True),
        ),
    ]
